### ISSUE TITLE
Docker not installed by default on my system

### ISSUE THREAD

**Issue by d--** [jdenen/mobile-suit-emacs#5]
I want to install a 133MB platform-specific dependency with or without a hypervisor before I install my 3MB packaged editor.  Code running natively bothers me as well, so this is perfect for my Windows PC.

Please provide platform specific links to install Docker.  Also, what is a package manager?

**Comment by jdenen** [comment]
I knew you would love this.

1. MacOS is a 2nd class citizen in Emacs land. Running it out of Docker does provide some benefit.
2. I've learned more about Docker doing this than anything professionally.
3. I really enjoy scripting stuff in Emacs Lisp.
4. I miss you.
